# Generated by Django 4.1.7 on 2023-03-24 09:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('SeedPinkApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='description_file',
        ),
        migrations.AddField(
            model_name='posts',
            name='write_blog',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
