# Generated by Django 4.1.7 on 2023-03-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeedPinkApp', '0003_alter_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title_picture_alt',
            field=models.CharField(default=models.CharField(max_length=200), max_length=30),
        ),
    ]
