# Generated by Django 4.1.7 on 2023-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeedPinkApp', '0004_posts_title_picture_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title_picture_alt',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_name',
            field=models.CharField(default='Abdul Moez', max_length=100),
        ),
    ]
