# Generated by Django 4.1.7 on 2023-03-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeedPinkApp', '0006_remove_portfolio_description_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title_picture_alt',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='', null=True, unique=True),
        ),
    ]
