# Generated by Django 4.1.7 on 2023-04-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeedPinkApp', '0007_portfolio_title_picture_alt_alter_portfolio_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
